# Generated by Django 5.0.14 on 2026-01-09 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('display_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제품명')),
                ('color_class', models.CharField(help_text='예: bg-green-500', max_length=50, verbose_name='Tailwind 색상 클래스')),
                ('display_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='예: 2512.2', max_length=50, verbose_name='버전 번호')),
                ('is_active', models.BooleanField(default=False, verbose_name='기본 버전')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='artifacts.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 버전',
                'verbose_name_plural': '제품 버전',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='artifacts/%Y/%m/', verbose_name='파일')),
                ('version_string', models.CharField(help_text='예: 5.18.0', max_length=50, verbose_name='산출물 버전')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드한 사용자')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='artifacts.category', verbose_name='카테고리')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='artifacts.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '산출물',
                'verbose_name_plural': '산출물',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'category', '-created_at'], name='artifacts_a_product_ad772f_idx')],
            },
        ),
    ]
