# Generated by Django 5.0.14 on 2026-01-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='국가 코드')),
                ('name', models.CharField(max_length=100, verbose_name='국가명')),
                ('flag_emoji', models.CharField(default='🌐', max_length=10, verbose_name='국기 이모지')),
                ('display_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '국가',
                'verbose_name_plural': '국가',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='artifact',
            name='artifacts_a_product_ad772f_idx',
        ),
        migrations.AddField(
            model_name='artifact',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='artifacts.country', verbose_name='국가'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['country', 'product', 'category', '-created_at'], name='artifacts_a_country_f39718_idx'),
        ),
    ]
