# Generated by Django 5.0.14 on 2026-01-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_icon',
            field=models.CharField(blank=True, help_text='예: free-icon-flag-KR.png', max_length=100, verbose_name='국기 아이콘'),
        ),
    ]
