# Generated by Django 5.0.14 on 2026-01-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0003_country_flag_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.CharField(choices=[('consulting', '컨설팅'), ('business', '사업'), ('marketing', '마케팅')], default='consulting', max_length=20, verbose_name='담당 부서'),
        ),
    ]
