# Generated by Django 5.0.14 on 2026-01-28 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0004_category_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryDisabled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='비활성화 일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_products', to='artifacts.category', verbose_name='카테고리')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='비활성화한 관리자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disabled_categories', to='artifacts.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '비활성화된 셀',
                'verbose_name_plural': '비활성화된 셀',
                'indexes': [models.Index(fields=['product', 'category'], name='artifacts_p_product_9ba495_idx')],
                'unique_together': {('product', 'category')},
            },
        ),
    ]
