# Generated by Django 5.0.14 on 2026-01-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0005_productcategorydisabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productcategorydisabled',
            name='artifacts_p_product_9ba495_idx',
        ),
        migrations.AlterUniqueTogether(
            name='productcategorydisabled',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productcategorydisabled',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disabled_cells', to='artifacts.country', verbose_name='국가'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productcategorydisabled',
            unique_together={('country', 'product', 'category')},
        ),
        migrations.AddIndex(
            model_name='productcategorydisabled',
            index=models.Index(fields=['country', 'product', 'category'], name='artifacts_p_country_f24a6c_idx'),
        ),
    ]
