# Generated by Django 5.0.14 on 2026-01-29 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0006_remove_productcategorydisabled_artifacts_p_product_9ba495_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='로그인 시도한 username (실패 시에도 기록)', max_length=150, verbose_name='사용자명')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, help_text='브라우저 및 OS 정보', verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, verbose_name='성공 여부')),
                ('failure_reason', models.CharField(blank=True, help_text='로그인 실패 시 이유', max_length=255, verbose_name='실패 이유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시도 시간')),
                ('user', models.ForeignKey(blank=True, help_text='로그인 성공 시 User 객체', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '로그인 시도',
                'verbose_name_plural': '로그인 시도',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='artifacts_l_created_4e688a_idx'), models.Index(fields=['username', '-created_at'], name='artifacts_l_usernam_b4da8f_idx'), models.Index(fields=['success', '-created_at'], name='artifacts_l_success_ba70d0_idx')],
            },
        ),
    ]
