# Generated by Django 5.0.14 on 2026-01-30 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0007_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_type', models.CharField(choices=[('single', '개별 다운로드'), ('bulk', '일괄 다운로드')], max_length=10, verbose_name='다운로드 유형')),
                ('artifact_count', models.IntegerField(default=0, help_text='일괄 다운로드 시 ZIP에 포함된 파일 수', verbose_name='다운로드된 산출물 수')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, help_text='브라우저 및 OS 정보', verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='다운로드 시간')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='artifacts.artifact', verbose_name='산출물')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='artifacts.country', verbose_name='국가')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to='artifacts.product', verbose_name='제품')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_logs', to=settings.AUTH_USER_MODEL, verbose_name='다운로드한 사용자')),
            ],
            options={
                'verbose_name': '다운로드 로그',
                'verbose_name_plural': '다운로드 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='artifacts_d_created_be5fc1_idx'), models.Index(fields=['user', '-created_at'], name='artifacts_d_user_id_62f9d1_idx'), models.Index(fields=['download_type', '-created_at'], name='artifacts_d_downloa_537e35_idx')],
            },
        ),
    ]
