# Generated by Django 5.0.14 on 2026-01-30 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0008_downloadlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_snapshot', models.JSONField(blank=True, help_text='삭제 시 파일 정보 보존 (JSON)', null=True, verbose_name='파일 정보 스냅샷')),
                ('username', models.CharField(max_length=150, verbose_name='사용자명')),
                ('action', models.CharField(choices=[('upload', '업로드'), ('delete', '삭제')], max_length=10, verbose_name='활동 유형')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, help_text='브라우저 및 OS 정보', verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, help_text='추가 메타데이터 (JSON)', null=True, verbose_name='추가 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='활동 시간')),
            ],
            options={
                'verbose_name': '파일 활동 로그',
                'verbose_name_plural': '파일 활동 로그',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='downloadlog',
            name='artifacts_d_user_id_62f9d1_idx',
        ),
        migrations.AddField(
            model_name='downloadlog',
            name='username',
            field=models.CharField(default='system', help_text='다운로드한 사용자명', max_length=150, verbose_name='사용자명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='artifact_count',
            field=models.IntegerField(default=0, help_text='일괄 다운로드 시 포함된 파일 개수', verbose_name='다운로드된 파일 수'),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_downloads', to='artifacts.country', verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_downloads', to='artifacts.product', verbose_name='제품'),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='downloadlog',
            index=models.Index(fields=['username', '-created_at'], name='artifacts_d_usernam_cc9fe3_idx'),
        ),
        migrations.AddField(
            model_name='artifactactivitylog',
            name='artifact',
            field=models.ForeignKey(blank=True, help_text='삭제된 경우 NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='artifacts.artifact', verbose_name='산출물'),
        ),
        migrations.AddField(
            model_name='artifactactivitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_activities', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddIndex(
            model_name='artifactactivitylog',
            index=models.Index(fields=['-created_at'], name='artifacts_a_created_787de0_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactactivitylog',
            index=models.Index(fields=['username', '-created_at'], name='artifacts_a_usernam_b107c4_idx'),
        ),
        migrations.AddIndex(
            model_name='artifactactivitylog',
            index=models.Index(fields=['action', '-created_at'], name='artifacts_a_action_a6c4c4_idx'),
        ),
    ]
