# Generated by Django 5.0.14 on 2026-01-30 06:31

import artifacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0009_artifactactivitylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='file',
            field=models.FileField(upload_to=artifacts.models.artifact_upload_path, verbose_name='파일'),
        ),
    ]
