# Generated by Django 5.0.14 on 2026-02-04 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0010_alter_artifact_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='웹훅을 식별하기 위한 이름', max_length=100, verbose_name='웹훅 이름')),
                ('webhook_url', models.URLField(help_text='Discord 웹훅 URL', verbose_name='웹훅 URL')),
                ('is_active', models.BooleanField(default=True, help_text='웹훅 활성화 여부', verbose_name='활성화')),
                ('event_file_upload', models.BooleanField(default=True, verbose_name='파일 업로드 알림')),
                ('event_file_delete', models.BooleanField(default=True, verbose_name='파일 삭제 알림')),
                ('event_download_single', models.BooleanField(default=False, help_text='개별 파일 다운로드 알림 (많을 수 있음)', verbose_name='개별 다운로드 알림')),
                ('event_download_bulk', models.BooleanField(default=True, verbose_name='일괄 다운로드 알림')),
                ('event_admin_activity', models.BooleanField(default=True, help_text='카테고리/제품 관리, 셀 토글 등', verbose_name='관리자 활동 알림')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '웹훅',
                'verbose_name_plural': '웹훅',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='artifacts_w_is_acti_44913d_idx')],
            },
        ),
    ]
