"""
Django settings for docsparrow project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f!%d#nvsghb@-yjwpw4hb2m$$s(rwsgimvqp+i_kcr29b=y&bc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'artifacts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'docsparrow.urls'

# Authentication URLs
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_REDIRECT_URL = '/'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'docsparrow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# CACHE CONFIGURATION
# ==============================================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'docsparrow-cache',
        'TIMEOUT': 300,  # 5 minutes default
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 0  # Don't cache entire pages by default
CACHE_MIDDLEWARE_KEY_PREFIX = 'docsparrow'

# ==============================================================================
# SESSION CONFIGURATION
# ==============================================================================

# Session security settings
SESSION_COOKIE_AGE = 86400  # 24 hours (instead of 14 days default)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access (XSS protection)
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_SAVE_EVERY_REQUEST = False  # Only save when session is modified
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Remember user for SESSION_COOKIE_AGE

# ==============================================================================
# CSRF CONFIGURATION
# ==============================================================================

CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to read csrftoken
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # Use cookie-based CSRF tokens

# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

# Security headers
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking

# For production deployment (currently disabled for development)
# SECURE_SSL_REDIRECT = True  # Redirect all HTTP to HTTPS
# SECURE_HSTS_SECONDS = 31536000  # Enable HSTS
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# ==============================================================================
# LDAP / ACTIVE DIRECTORY AUTHENTICATION
# ==============================================================================
# Fasoo AD 서버 연동 설정 (ldap3 기반 커스텀 백엔드)
#
# 환경변수로 오버라이드 가능 (선택):
#   LDAP_SERVER_URI       - AD 서버 주소 (기본값: ldap://192.168.200.5:389)
#   LDAP_USER_SEARCH_BASE - 사용자 검색 Base DN (기본값: OU=FASOOCOM,DC=fasoo,DC=com)
#   LDAP_ENABLED          - false로 설정 시 LDAP 비활성화
# ==============================================================================

# 환경변수로 LDAP 비활성화 가능 (LDAP_ENABLED=false 설정 시)
LDAP_ENABLED = os.environ.get('LDAP_ENABLED', 'true').lower() != 'false'

if LDAP_ENABLED:
    # --- AD 서버 접속 정보 ---
    LDAP_SERVER_URI = os.environ.get(
        'LDAP_SERVER_URI', 'ldap://192.168.200.5:389'
    )

    # --- Direct Bind 방식 (서비스 계정 불필요) ---
    # 사용자가 입력한 username에 @fasoo.com을 붙여 AD에 직접 바인드
    LDAP_USER_DN_TEMPLATE = '%(user)s@fasoo.com'

    # --- 사용자 검색 Base DN ---
    LDAP_USER_SEARCH_BASE = os.environ.get(
        'LDAP_USER_SEARCH_BASE', 'OU=FASOOCOM,DC=fasoo,DC=com'
    )

    # --- AD 속성 → Django User 필드 매핑 ---
    LDAP_USER_ATTR_MAP = {
        "first_name": "cn",                  # AD 이름(cn) → Django first_name
        "last_name": "sn",                   # AD 성(sn) → Django last_name
        "email": "userPrincipalName",        # AD UPN → Django email
    }

    # LDAP 인증 성공 시 매번 AD 정보로 User 업데이트 (동적 사용자 생성)
    LDAP_ALWAYS_UPDATE_USER = True

    # --- 인증 백엔드 순서: LDAP 먼저, 실패 시 로컬 DB Fallback ---
    AUTHENTICATION_BACKENDS = [
        "artifacts.ldap_backend.LDAPBackend",          # 1순위: AD/LDAP 인증
        "django.contrib.auth.backends.ModelBackend",   # 2순위: 로컬 DB 인증 (Fallback)
    ]

    # --- LDAP 디버그 로깅 (개발 환경에서만 사용) ---
    import logging
    _ldap_logger = logging.getLogger('ldap_auth')
    _ldap_logger.addHandler(logging.StreamHandler())
    _ldap_logger.setLevel(logging.DEBUG if DEBUG else logging.WARNING)

else:
    # LDAP 비활성화 시 기본 인증 백엔드만 사용
    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
    ]
